### ISSUE TITLE
Player in gameplay levels must be able to switch armed/unarmed state

### ISSUE THREAD

**Issue by JameeKim** [Elite-Centennial/Remembering-Wallace#24]
### Requirements

- The player character starts with an unarmed state with the sword sheathed.
- When the corresponding player input is detected, the player character switches to an armed state by pulling out the sword.
- In an armed state, the player character holds the sword in the right hand. The character also has a different posture.
- When the input is detected, the player character puts back the sword and goes back to an unarmed state.
- The input for changing the states must be handled appropriately when the player triggers it while the transition is happening.

### System Design

For this feature, the following things should be implemented:

1. Integration with the input and the ability system component
   - Enables input pressed/released events in abilities
   - Enables automatic activation of abilities from player input
1. State tracking for the player character (or any other combat units) using Gameplay Tags
   - The system itself is already provided, but we need to establish the structure of our Gameplay Tags.

The default implementation of binding player input to ability activation `UAbilitySystemComponent::BindAbilityActivationToInputComponent` expects an enum whose values have matching names to the actions defined in project input settings. This puts some restrictions on the names we can assign to the input actions since the enum needs to be defined in C++ to allow other parts of code to reference the enum type.

### Tasks

- [x] Create an enum for input IDs
- [x] Modify `UWallaceAbilitySystemComponent` to use the created enum to bind to input component
- [x] Create abilities for switching armed/unarmed states
  - [x] Gameplay Tags
  - [x] Animations
